- name: Demo on package installation 
  hosts: all 
  become: yes                              # Privilege Escalation
  tasks: 
    - name: Installing nginx 
      ansible.builtin.package:
        name: nginx 
        state: present