- name: Demo on copy 
  hosts: all 
  become: yes                              # Privilege Escalation
  tasks: 
    - name: Copying the proxy file to the remote nodes
      ansible.builtin.copy:
        src: proxy.conf 
        dest: /home/centos/proxy.conf 